In [2]:
import os
import sys
import time
import datetime
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import msgpack as mp
import msgpack_numpy as mpn
import cv2
sys.path.append('..')
from support.camera_calibration import calibrate_camera_from_file

In [5]:
_pth = os.getcwd()
_pth = os.path.dirname(_pth)

_folder_name = "calibration8"
_webcam_pth = os.path.join(_pth,"recording_programs","test_data","single_cam_oct_8", _folder_name,"webcam_color.msgpack")
_webcam_ts = os.path.join(_pth,"recording_programs", "test_data","single_cam_oct_8",_folder_name,"webcam_timestamp.msgpack")
_webcam_pth

'c:\\Users\\CMC\\Documents\\openposelibs\\pose\\skateboard_gui\\recording_programs\\test_data\\single_cam_oct_8\\calibration8\\webcam_color.msgpack'

In [6]:
calibrate_camera_from_file(_webcam_pth,save_to_dir = True ,img_flip = False, cvt_color=False, saving_name = "webcam_calibration")

100%|██████████| 442/442 [00:01<00:00, 364.11it/s]


Found [ 0  1  2  3  4  5  6  7  8  9 10 11] unique markers
corners_list:  (1725, 1, 4, 2)
Calibrating camera .... Please wait...
 Camera matrix is 
 [[846.90488435   0.         372.81015759]
 [  0.         853.59910004 288.58970643]
 [  0.           0.           1.        ]] 
 And is stored in AR_CALIBRATION.msgpack file along with distortion coefficients : 
 [[-0.02432381  0.98163415  0.01791763  0.00883766 -6.35247477]]
