In [1]:
import os
import sys
import time
import datetime
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import msgpack as mp
import msgpack_numpy as mpn
import cv2
sys.path.append('..')
from support.camera_calibration import calibrate_camera_from_file

In [2]:
_pth = os.getcwd()
_pth = os.path.dirname(_pth)

_folder_name = "calibration7"
_webcam_pth = os.path.join(_pth,"recording_programs","test_data","single_cam_oct_7", _folder_name,"webcam_color.msgpack")
_webcam_ts = os.path.join(_pth,"recording_programs", "test_data","single_cam_oct_7",_folder_name,"webcam_timestamp.msgpack")
_webcam_pth

'c:\\Users\\Sujith\\Documents\\Projects\\skateboard_gui\\recording_programs\\test_data\\single_cam_oct_7\\calibration7\\webcam_color.msgpack'

In [3]:
calibrate_camera_from_file(_webcam_pth,save_to_dir = True ,img_flip = False, cvt_color=False, saving_name = "webcam_calibration")

100%|██████████| 393/393 [00:02<00:00, 148.25it/s]


Found [ 0  1  2  3  4  5  6  7  8  9 10 11] unique markers
corners_list:  (1649, 1, 4, 2)
Calibrating camera .... Please wait...
 Camera matrix is 
 [[812.72185392   0.         361.36990099]
 [  0.         826.1836205  340.68486577]
 [  0.           0.           1.        ]] 
 And is stored in AR_CALIBRATION.msgpack file along with distortion coefficients : 
 [[-0.06191804  0.72418337  0.02897288  0.0049847  -2.82544447]]
